In [2]:
import pandas as pd

df = pd.read_csv('BaseDeDados1.csv')

df

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$)
0,Bar do Bituca,"R$ 34.769,00","R$ 10.747,00","R$ 3.267,00"
1,Café Curva,"R$ 43.693,00","R$ 33.551,00","R$ 3.528,00"
2,Tasca da Tia,"R$ 21.396,00","R$ 34.382,00","R$ 13.394,00"
3,Rango Rápido,"R$ 77.187,00","R$ 8.189,00","R$ 5.556,00"
4,Flor de Sal,"R$ 42.480,00","R$ 39.677,00","R$ 5.890,00"
5,República Espresso,"R$ 56.434,00","R$ 27.118,00","R$ 10.838,00"
6,Quintal Zé,"R$ 40.658,00","R$ 11.005,00","R$ 13.080,00"
7,Santa Farra,"R$ 33.942,00","R$ 29.042,00","R$ 7.393,00"
8,Cantinho do Chef,"R$ 72.001,00","R$ 9.899,00","R$ 12.627,00"
9,Vibe Bar,"R$ 33.431,00","R$ 32.118,00","R$ 10.792,00"

In [3]:

print(df[["Faturamento Mensal (R$)", "Custo Operacional (R$)"]].head())

  Faturamento Mensal (R$) Custo Operacional (R$)
0            R$ 34.769,00           R$ 10.747,00
1            R$ 43.693,00           R$ 33.551,00
2            R$ 21.396,00           R$ 34.382,00
3            R$ 77.187,00            R$ 8.189,00
4            R$ 42.480,00           R$ 39.677,00

In [4]:
df["Faturamento Mensal (R$)"] = df["Faturamento Mensal (R$)"].astype(str).str.strip()
df["Custo Operacional (R$)"] = df["Custo Operacional (R$)"].astype(str).str.strip()
df["Impostos Pagos (R$)"] = df["Impostos Pagos (R$)"].astype(str).str.strip()

df["Faturamento Mensal (R$)"] = df["Faturamento Mensal (R$)"].replace({'R\$': '', '\.': '', ',': '.'}, regex=True)
df["Custo Operacional (R$)"] = df["Custo Operacional (R$)"].replace({'R\$': '', '\.': '', ',': '.'}, regex=True)
df["Impostos Pagos (R$)"] = df["Impostos Pagos (R$)"].replace({'R\$': '', '\.': '', ',': '.'}, regex=True)

df["Faturamento Mensal (R$)"] = pd.to_numeric(df["Faturamento Mensal (R$)"], errors='coerce')
df["Custo Operacional (R$)"] = pd.to_numeric(df["Custo Operacional (R$)"], errors='coerce')
df["Impostos Pagos (R$)"] = pd.to_numeric(df["Impostos Pagos (R$)"], errors='coerce')

df

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$)
0,Bar do Bituca,34769.0,10747.0,3267.0
1,Café Curva,43693.0,33551.0,3528.0
2,Tasca da Tia,21396.0,34382.0,13394.0
3,Rango Rápido,77187.0,8189.0,5556.0
4,Flor de Sal,42480.0,39677.0,5890.0
5,República Espresso,56434.0,27118.0,10838.0
6,Quintal Zé,40658.0,11005.0,13080.0
7,Santa Farra,33942.0,29042.0,7393.0
8,Cantinho do Chef,72001.0,9899.0,12627.0
9,Vibe Bar,33431.0,32118.0,10792.0

In [5]:
df["Lucro Operacional (R$)"] = df["Faturamento Mensal (R$)"] - df["Custo Operacional (R$)"]

df["Margem Operacional (%)"] = ((df["Lucro Operacional (R$)"] / df["Faturamento Mensal (R$)"]) * 100).round(2)

df["Percentual de Impostos (%)"] = ((df["Impostos Pagos (R$)"] / df["Faturamento Mensal (R$)"]) * 100).round(2)

df["Rentabilidade Líquida (R$)"] = df["Lucro Operacional (R$)"] - df["Impostos Pagos (R$)"]
df["Rentabilidade Liquida (%)"] = ((df["Lucro Operacional (R$)"] - df["Impostos Pagos (R$)"]) / df["Faturamento Mensal (R$)"] * 100).round(2)



df

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$),Lucro Operacional (R$),Margem Operacional (%),Percentual de Impostos (%),Rentabilidade Líquida (R$),Rentabilidade Liquida (%)
0,Bar do Bituca,34769.0,10747.0,3267.0,24022.0,69.09,9.40,20755.0,59.69
1,Café Curva,43693.0,33551.0,3528.0,10142.0,23.21,8.07,6614.0,15.14
2,Tasca da Tia,21396.0,34382.0,13394.0,-12986.0,-60.69,62.60,-26380.0,-123.29
3,Rango Rápido,77187.0,8189.0,5556.0,68998.0,89.39,7.20,63442.0,82.19
4,Flor de Sal,42480.0,39677.0,5890.0,2803.0,6.60,13.87,-3087.0,-7.27
5,República Espresso,56434.0,27118.0,10838.0,29316.0,51.95,19.20,18478.0,32.74
6,Quintal Zé,40658.0,11005.0,13080.0,29653.0,72.93,32.17,16573.0,40.76
7,Santa Farra,33942.0,29042.0,7393.0,4900.0,14.44,21.78,-2493.0,-7.34
8,Cantinho do Chef,72001.0,9899.0,12627.0,62102.0,86.25,17.54,49475.0,68.71
9,Vibe Bar,33431.0,32118.0,10792.0,1313.0,3.93,32.28,-9479.0,-28.35

In [6]:
clientes_maior_margem = df.sort_values(by="Margem Operacional (%)", ascending=False).head(5)

clientes_maior_margem

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$),Lucro Operacional (R$),Margem Operacional (%),Percentual de Impostos (%),Rentabilidade Líquida (R$),Rentabilidade Liquida (%)
3,Rango Rápido,77187.0,8189.0,5556.0,68998.0,89.39,7.20,63442.0,82.19
8,Cantinho do Chef,72001.0,9899.0,12627.0,62102.0,86.25,17.54,49475.0,68.71
6,Quintal Zé,40658.0,11005.0,13080.0,29653.0,72.93,32.17,16573.0,40.76
0,Bar do Bituca,34769.0,10747.0,3267.0,24022.0,69.09,9.40,20755.0,59.69
5,República Espresso,56434.0,27118.0,10838.0,29316.0,51.95,19.20,18478.0,32.74

In [7]:
clientes_mais_impostos = df.sort_values(by="Percentual de Impostos (%)", ascending=False).head(5)

clientes_mais_impostos

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$),Lucro Operacional (R$),Margem Operacional (%),Percentual de Impostos (%),Rentabilidade Líquida (R$),Rentabilidade Liquida (%)
2,Tasca da Tia,21396.0,34382.0,13394.0,-12986.0,-60.69,62.60,-26380.0,-123.29
9,Vibe Bar,33431.0,32118.0,10792.0,1313.0,3.93,32.28,-9479.0,-28.35
6,Quintal Zé,40658.0,11005.0,13080.0,29653.0,72.93,32.17,16573.0,40.76
7,Santa Farra,33942.0,29042.0,7393.0,4900.0,14.44,21.78,-2493.0,-7.34
5,República Espresso,56434.0,27118.0,10838.0,29316.0,51.95,19.20,18478.0,32.74

In [8]:
clientes_rentabilidade = df.sort_values(by="Rentabilidade Líquida (R$)", ascending=False)

clientes_rentabilidade

,Cliente,Faturamento Mensal (R$),Custo Operacional (R$),Impostos Pagos (R$),Lucro Operacional (R$),Margem Operacional (%),Percentual de Impostos (%),Rentabilidade Líquida (R$),Rentabilidade Liquida (%)
3,Rango Rápido,77187.0,8189.0,5556.0,68998.0,89.39,7.20,63442.0,82.19
8,Cantinho do Chef,72001.0,9899.0,12627.0,62102.0,86.25,17.54,49475.0,68.71
0,Bar do Bituca,34769.0,10747.0,3267.0,24022.0,69.09,9.40,20755.0,59.69
5,República Espresso,56434.0,27118.0,10838.0,29316.0,51.95,19.20,18478.0,32.74
6,Quintal Zé,40658.0,11005.0,13080.0,29653.0,72.93,32.17,16573.0,40.76
1,Café Curva,43693.0,33551.0,3528.0,10142.0,23.21,8.07,6614.0,15.14
7,Santa Farra,33942.0,29042.0,7393.0,4900.0,14.44,21.78,-2493.0,-7.34
4,Flor de Sal,42480.0,39677.0,5890.0,2803.0,6.60,13.87,-3087.0,-7.27
9,Vibe Bar,33431.0,32118.0,10792.0,1313.0,3.93,32.28,-9479.0,-28.35
2,Tasca da Tia,21396.0,34382.0,13394.0,-12986.0,-60.69,62.60,-26380.0,-123.29

In [9]:
import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))
plt.bar(df['Cliente'], df['Margem Operacional (%)'], color='skyblue')
plt.title('Margem Operacional dos Clientes')
plt.xlabel('Clientes')
plt.ylabel('Margem Operacional (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('margem_operacional.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.bar(df['Cliente'], df['Percentual de Impostos (%)'], color='salmon')
plt.title('Percentual de Impostos sobre o Faturamento')
plt.xlabel('Clientes')
plt.ylabel('% Impostos sobre Faturamento')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('impostos_percentual.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.bar(df['Cliente'], df['Rentabilidade Líquida (R$)'], color='lightgreen')
plt.title('Rentabilidade Líquida dos Clientes')
plt.xlabel('Clientes')
plt.ylabel('Rentabilidade Líquida (R$)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('rentabilidade_liquida.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.bar(df['Cliente'], df['Rentabilidade Liquida (%)'], color='orange')
plt.title('Rentabilidade Líquida (%) dos Clientes')
plt.xlabel('Clientes')
plt.ylabel('Rentabilidade Líquida (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('rentabilidade_liquida_percentual.png')
plt.close()

In [10]:
relatorio = """
Relatório de Análise Financeira dos Clientes

1. Clientes com maior margem operacional:
{}
 
2. Clientes que pagam mais impostos proporcionalmente ao faturamento:
{}

3. Ranking dos clientes mais rentáveis (Lucro Operacional - Impostos):
{}

""".format(clientes_maior_margem[["Cliente", "Margem Operacional (%)"]].to_string(index=False),
           clientes_mais_impostos[["Cliente", "Percentual de Impostos (%)"]].to_string(index=False),
           clientes_rentabilidade[["Cliente", "Rentabilidade Líquida (R$)"]].to_string(index=False))

print(relatorio)

Relatório de Análise Financeira dos Clientes

1. Clientes com maior margem operacional:
           Cliente  Margem Operacional (%)
      Rango Rápido                   89.39
  Cantinho do Chef                   86.25
        Quintal Zé                   72.93
     Bar do Bituca                   69.09
República Espresso                   51.95

2. Clientes que pagam mais impostos proporcionalmente ao faturamento:
           Cliente  Percentual de Impostos (%)
      Tasca da Tia                       62.60
          Vibe Bar                       32.28
        Quintal Zé                       32.17
       Santa Farra                       21.78
República Espresso                       19.20

3. Ranking dos clientes mais rentáveis (Lucro Operacional - Impostos):
           Cliente  Rentabilidade Líquida (R$)
      Rango Rápido                     63442.0
  Cantinho do Chef                     49475.0
     Bar do Bituca                     20755.0
República Espresso                     18478.0
        Quintal Zé                     16573.0
        Café Curva                      6614.0
       Santa Farra                     -2493.0
       Flor de Sal                     -3087.0
          Vibe Bar                     -9479.0
      Tasca da Tia                    -26380.0

In [11]:
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()

pdf.set_font("Arial", size=16, style='B')
pdf.cell(200, 10, txt="Relatório de Análise Financeira dos Clientes", ln=True, align='C')

pdf.ln(10) 

pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, relatorio)

pdf.ln(10) 

pdf.image('margem_operacional.png', x=10, w=180)
pdf.ln(90)  

pdf.image('impostos_percentual.png', x=10, w=180)
pdf.ln(90) 

pdf.image('rentabilidade_liquida.png', x=10, w=180)
pdf.ln(90)

pdf.image('rentabilidade_liquida_percentual.png', x=10, w=180)

pdf.output("relatorio_financeiro.pdf")

''

In [18]:
import plotly.graph_objects as go
import plotly.express as px

df_sorted_margem = df.sort_values(by='Margem Operacional (%)', ascending=False)
df_sorted_impostos = df.sort_values(by='Percentual de Impostos (%)', ascending=False)
df_sorted_rentabilidade = df.sort_values(by='Rentabilidade Líquida (R$)', ascending=False)
df_sorted_rentabilidade_percentual = df.sort_values(by='Rentabilidade Liquida (%)', ascending=False)

fig1 = go.Figure(data=[go.Bar(
    x=df_sorted_margem['Cliente'],
    y=df_sorted_margem['Margem Operacional (%)'],
    text=df_sorted_margem['Margem Operacional (%)'],
    textposition='auto',  
    marker_color='skyblue'
)])

fig1.update_layout(
    title="Margem Operacional dos Clientes (%)",
    xaxis_title="Clientes",
    yaxis_title="Margem Operacional (%)",
    xaxis_tickangle=-45,
    showlegend=False,
    template="plotly_dark"  
)

fig1.show()

fig2 = go.Figure(data=[go.Bar(
    x=df_sorted_impostos['Cliente'],
    y=df_sorted_impostos['Percentual de Impostos (%)'],
    text=df_sorted_impostos['Percentual de Impostos (%)'],
    textposition='auto',  
    marker_color='salmon'
)])

fig2.update_layout(
    title="Percentual de Impostos sobre o Faturamento (%)",
    xaxis_title="Clientes",
    yaxis_title="% Impostos sobre Faturamento",
    xaxis_tickangle=-45,
    showlegend=False,
    template="plotly_dark"  
)

fig2.show()

fig3 = go.Figure(data=[go.Bar(
    x=df_sorted_rentabilidade['Cliente'],
    y=df_sorted_rentabilidade['Rentabilidade Líquida (R$)'],
    text=df_sorted_rentabilidade['Rentabilidade Líquida (R$)'],
    textposition='auto', 
    marker_color='lightgreen',
    texttemplate='%{text:.2f}'  
)])

fig3.update_layout(
    title="Rentabilidade Líquida dos Clientes (R$)",
    xaxis_title="Clientes",
    yaxis_title="Rentabilidade Líquida (R$)",
    xaxis_tickangle=-45,
    showlegend=False,
    template="plotly_dark" 
)

fig3.show()

fig4 = go.Figure(data=[go.Bar(
    x=df_sorted_rentabilidade_percentual['Cliente'],
    y=df_sorted_rentabilidade_percentual['Rentabilidade Liquida (%)'],
    text=df_sorted_rentabilidade_percentual['Rentabilidade Liquida (%)'],
    textposition='auto', 
)])

fig4.update_layout(
    title="Rentabilidade Liquida (%) dos Clientes",
    xaxis_title="Clientes",
    yaxis_title="Rentabilidade Liquida (%)",
    xaxis_tickangle=-45,
    showlegend=False,
    template="plotly_dark"  
)

fig4.show()

In [ ]:

df.to_csv('AtualizadoBase.csv', index=False)

df.to_excel('AtualizadoBase1.xlsx', index=False, engine='openpyxl')